Do not panic in peer connection IO handling thread.
I keep seeing these panics:

```
cargo-package> thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /build/source/fedimint-server/src/net/peers.rs:439:37
cargo-package> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
cargo-package> thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /build/source/fedimint-server/src/net/peers.rs:297:37
cargo-package> thread 'thread 'tokio-runtime-worker' panicked at 'tokio-runtime-workerPeer connection was dropped', /build/source/fedimint-server/src/net/peers.rs:439:37
```

when running integration tests, and they are spooking me.

It seems the IO thread should just finish instead of panicking and the
cause of the panic is the parent thread is gone, and nothing to do with
the connection itself (unless I misunderstand the code).