fix: our ring fork not compiling c code for wasm
The actual fix:

https://github.com/dpc/ring/commit/5493e7e76d0d8fb1d3cbb0be9c4944700741b802

The reason the poly stuff was missing was:

https://github.com/dpc/ring/blob/5493e7e76d0d8fb1d3cbb0be9c4944700741b802/build.rs#L326

which took me embarrassingly long to figure out.

I just re-introduced `wasm32_c`, to keep the changes minimal.

Fix #2843

I confirmed that the "import from env" is gone. Though the repro in it now fails with:

```
Error: non-200 response code: 500
{"value":{"error":"unknown error","message":"Failed to decode response from marionette","stacktrace":""}}
error: test failed, to rerun pass `--lib`
```

but that seems something entirely different.